### ISSUE TITLE
crossbeam-skiplist 0.1 release

### ISSUE THREAD

**Issue by taiki-e** [crossbeam-rs/crossbeam#635]
This is a tracking issue for the initial release of crossbeam-skiplist.

## TODO

- [x] Add docs (https://github.com/crossbeam-rs/crossbeam/issues/503#issuecomment-631679442)
  - [x] Crate-level docs; done in #535
  - [x] Docs for `SkipMap`; done in #535
  - [x] Docs for `SkipSet`; done in #655
  - [x] Docs for `SkipList`; done in #655
- [x] Update readme; done in #887

## Open issues

- [ ]  Remove the `'static` bounds (#205)
- [ ] `Entry`'s name is misleading (https://github.com/crossbeam-rs/crossbeam/pull/535#issue-440783380); maybe good to rename to [`Cursor`](https://doc.rust-lang.org/stable/std/collections/linked_list/struct.Cursor.html)? (https://github.com/crossbeam-rs/crossbeam/pull/535#issuecomment-651188964)
- [x] `set::Entry` could implement `Deref<Target=T>` for convenience. (https://github.com/crossbeam-rs/crossbeam/pull/535#issue-440783380); done in #657
- memory leaks 
  - [ ] SkipList #614
  - [x] Skip{Map,Set} #671; fixed in #673
  - [x] Skip{Map,Set} #672; fixed in #673 
- [ ] re-export in crossbeam crate (#889)

**Comment by ryoqun** [comment]
@taiki-e Hi, I'm glad to see steady progress of this. We're potentially looking forward to using this for Solana's critically-important Accounts DB indexes if possible, which is 10 million entries already. Thanks for working on this.

**Comment by al8n** [comment]
Hi, is this crate ready for release?

**Comment by taiki-e** [comment]
It should be ready except that the readme needs to be updated a bit.

**Comment by MrCroxx** [comment]
Hi, sorry to bother, but can't wait to see this crate released, 🥰. Is there a release plan?

**Comment by taiki-e** [comment]
Release PR: https://github.com/crossbeam-rs/crossbeam/pull/888

**Comment by taiki-e** [comment]
Published https://crates.io/crates/crossbeam-skiplist/0.1.0
